name: "yamldiff"
version: "0.0.2"
usage: "Gets the differences between a helm values.yaml file and the upstream"
description: "Gets the differences between a helm values.yaml file and the upstream"
ignoreFlags: false
command: "python3 $HELM_PLUGIN_DIR/yamldifftool.py"
hooks:
  install: "if ! pip3 show pyyaml; then pip3 install -r $HELM_PLUGIN_DIR/requirements.txt; fi"
  update: "if ! pip3 show pyyaml; then pip3 install -r $HELM_PLUGIN_DIR/requirements.txt; fi"
