name: "yamldiff"
version: "0.0.3"
usage: "Gets the differences between a helm values.yaml file and the upstream"
description: "Gets the differences between a helm values.yaml file and the upstream"
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/dist/yamldifftool/yamldifftool"
hooks:
  install: "if ! pip3 show pyyaml; then pyinstaller yamldifftool.py; fi"
  update: "if ! pip3 show pyyaml; then pyinstaller yamldifftool.py; fi"
