name: Build yamldifftool
run-name: Build yamldifftool
on: [push]

jobs:
  Build-Packages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: pwd
      - run: pip3 install -r requirements.txt
      - run: pyinstaller yamldifftool.py
      - run: python3 test.py
      - run: python3 yamldifftool.py test/default_values.yaml test/large_copied_values.yaml
      - run: docker build -t tmpimage ./
      - run: docker run -v ./test:/home/app_user/test tmpimage python3 test/default_values.yaml test/large_copied_values.yaml

