name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version in plugin.yaml
        run: |
          VERSION=$(echo ${GITHUB_REF#refs/tags/})
          sed -i "s/version:.*/version: $VERSION/" plugin.yaml
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add plugin.yaml
          git commit -m "Bump version to $VERSION"
          git tag -d $VERSION
          git tag $VERSION
          git push origin HEAD:main

      - uses: ncipollo/release-action@v1
        name: Create GitHub Release
        id: create_release
        with:
          tag: ${{ github.ref }}
          name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.ref }} .

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/yamldifftool:${{ github.ref }}